services:
  - type: web
    runtime: static
    name: txhighway
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
